<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>1.3.8</Version>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon>Assets/Footprint.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets/Footprint.ico" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" />
    <ProjectReference Include="../Footprint.Core/Footprint.Core.csproj" />
  </ItemGroup>
</Project>
